import math
print('pi' + str(math.pi))
print('e   ' + str(math.e))
print('√4 ' + str(math.sqrt(4)))
print('4.1:   ' + str(math.ceil(4.1)))
print('4.9:   ' + str(math.floor(4.9)))
print('2^3:   ' + str(math.pow(2, 3)))
print('5!:   ' + str(math.factorial(5)))
print('log:   ' + str(math.log(10)))
print('log:   ' + str(math.log10(100)))
print('log:   ' + str(math.log2(8)))
print('log:   ' + str(math.log1p(2)))
print('2^   '+str(math.exp(2)))
print('2^   '+str(math.sin(math.pi / 2)))
print('xot:   ' + str(math.cos(math.pi / 2)))
print('xot:   ' + str(math.tan(math.pi / 2)))
print('deg:   ' + str(math.degrees(math.pi / 2)))
print('rAD:   ' + str(math.radians(90)))
